# Generated by Django 4.1 on 2022-10-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0002_fakultas_prodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='Fakultas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faperta.fakultas'),
        ),
    ]
