# Generated by Django 4.1 on 2022-10-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0004_rename_fakultas_mahasiswa_fakultas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='id_fakultas',
            new_name='id_Fakultas',
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='id_prodi',
            new_name='id_Prodi',
        ),
        migrations.RenameField(
            model_name='fakultas',
            old_name='id_fakultas',
            new_name='id_Fakultas',
        ),
        migrations.RenameField(
            model_name='fakultas',
            old_name='nama_fakultas',
            new_name='nama_Fakultas',
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='fakultas',
            new_name='Fakultas',
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='prodi',
            new_name='Prodi',
        ),
        migrations.RenameField(
            model_name='prodi',
            old_name='id_prodi',
            new_name='id_Prodi',
        ),
        migrations.RenameField(
            model_name='prodi',
            old_name='nama_prodi',
            new_name='nama_Prodi',
        ),
    ]
